server:
  port: 8088
  context-path: /ncocc

spring:
  application:
    name: NCOCC
  transaction:
    default-timeout: 60 #Default transaction timeout in seconds.
  datasource:
    hikari:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://106.15.177.118:3366/ncocc
      username: joshua
      password: "@njl123NJL"
      maximum-pool-size: 10
      minimum-idle: 5
  devtools:
    restart:
      enabled: true
    


  
      
    
  
